language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - composer self-update
  - cd ..
  - cp templavoila/Build/composer.json .
  - composer --dev install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv templavoila typo3conf/ext/templavoila
  - git clone https://github.com/typo3-ter/static_info_tables.git typo3conf/ext/static_info_tables

script:
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    ./bin/phpunit --colors -c typo3/sysext/core/Build/FunctionalTests.xml ./typo3conf/ext/templavoila/Tests/Functional/ApiTest.php

    echo;
    echo "Running unit tests";
    ./bin/phpunit --coverage-clover=./typo3conf/ext/templavoila/coverage.clover --colors -c typo3conf/ext/templavoila/Tests/Build/UnitTests.xml ./typo3conf/ext/templavoila/Tests/Unit/

after_script:
  - echo;
  - echo "Sending code coverage data";
  - cd ./typo3conf/ext/templavoila/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
